[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# SPA fallback - only catch unmatched routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
